#%RAML 1.0
title: WeighIn
version: v1.0
baseUri: https://weighin.wehackers.club

/cable:
  description: "Actioncable server"
  /all_comments_{client_id}:
    description: "Push all comments for the given URL to a specific client when it first subscribes to the channel"
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "user": {
                      "username": "harryliu",
                      "name": "Harry"
                    },
                    "body": "5555",
                    "createdAt": 123232412
                  }
                ]
  /new_comment_{url}:
    description: "Push new comment to all clients visiting the given URL"
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "message_type": "new_comment",
                  "comment": {
                    "user": {
                      "username": "harryliu",
                      "name": "Harry"
                    },
                    "body": "5555",
                    "createdAt": 123232412
                  }
                }
  /all_highlights_{client_id}:
    description: "Push all highlights for the given URL to a specific client when it first subscribes to the channel"
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "id": 21321312,
                    "color": "green",
                    "end": 78,
                    "domID": 2208,
                    "parentId": 43,
                    "previousSiblingId": -1,
                    "start": 7,
                    "position": 0
                  },
                  {
                    "id": 123213123,
                    "color": "red",
                    "end": 74,
                    "domID": 2209,
                    "parentId": 43,
                    "previousSiblingId": 2208,
                    "start": 6,
                    "position": 1
                  }
                ]
  /new_highlight_{url}:
    description: "Push new highlight to all clients visiting the given URL"
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "highlight": {
                    "id": 12312312,
                    "color": "green",
                    "end": 78,
                    "domID": 2208,
                    "parentId": 43,
                    "previousSiblingId": -1,
                    "start": 7,
                    "position": 0
                  },
                  "domIDsAfter": [
                    153,
                    154,
                    155
                  ]
                }
  /new_message_{highlight_id}:
    description: "Push new message to all clients visiting the message box for the given highlight"
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "highlightID": 2313213,
                  "user": {
                    "username": "harryliu",
                    "name": "Harry"
                  },
                  "body": "5555",
                  "createdAt": 123232412
                }

/urls/{url_id}:
  uriParameters:
    url_id:
      description: "Database ID for an URL"
      type: number
      example: 1244323
  /comments:
    post:
      description: "Add a comment to a given URL"
      headers:
        Username:
          description: Username of the user who created the comment
          example: harryliu
      body:
        application/json:
          example: |
            {
              "body": "5555"
            }
      responses:
          201:
  /highlights:
    post:
      description: "Add a highlight and increment position for highlights whose IDs are in highlightIDsAfterPosition"
      headers:
        Username:
          description: Username of the user who created the comment
          example: harryliu
      body:
        application/json:
          example: |
            {
              "highlight": {
                "id": 1232321,
                "color": "green",
                "end": 78,
                "domID": 2208,
                "parentId": 43,
                "previousSiblingId": -1,
                "start": 7,
                "position": 0
              },
              "domIDsAfter": [
                153,
                154,
                155
              ]
            }
      responses:
        201:
    /{highlight_id}/messages:
      get:
        description: "Get all messages for the given highlight"
        responses:
          200:
            body:
              application/json:
                example: |
                  [
                    {
                      "user": {
                        "username": "harryliu",
                        "name": "Harry"
                      },
                      "body": "5555",
                      "createdAt": 123232412
                    }
                  ]
      post:
        description: "Add a message to the given highlight"
        headers:
          Username:
            description: Username of the user who created the comment
            example: harryliu
        body:
          application/json:
            example: |
              {
                "body": "5555"
              }
        responses:
          201:
