#%RAML 1.0
title: WeighIn
version: v1.0
baseUri: https://weighin.wehackers.club

/urls/{url}:
  /comments:
    get:
      description: "Get all comments for the given URL"
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "user": {
                      "username": "harryliu",
                      "name": "Harry"
                    },
                    "comment": {
                      "body": "5555",
                      "createdAt": 123232412
                    }
                  }
                ]
    post:
      description: "Add a comment to a given URL"
      headers:
        Username:
          description: Username of the user who created the comment
          example: harryliu
      body:
        application/json:
          example: |
            {
              "body": "5555"
            }
      responses:
          201:
            body:
              application/json:
                example:
  /highlights:
    get:
      description: "Get all highlights for given URL"
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "color": "green",
                    "end": 78,
                    "id": 2208,
                    "parentId": 43,
                    "previousSiblingId": -1,
                    "start": 7,
                    "position": 0
                  },
                  {
                    "color": "red",
                    "end": 74,
                    "id": 2209,
                    "parentId": 43,
                    "previousSiblingId": 2208,
                    "start": 6,
                    "position": 1
                  }
                ]
    post:
      description: "Add a highlight and increment position for highlights whose IDs are in highlightIDsAfterPosition"
      headers:
        Username:
          description: Username of the user who created the comment
          example: harryliu
      body:
        application/json:
          example: |
            {
              "highlight": {
                "color": "green",
                "end": 78,
                "id": 2208,
                "parentId": 43,
                "previousSiblingId": -1,
                "start": 7,
                "position": 0
              },
              "highlightIDsAfterPosition": [
                153,
                154,
                155
              ]
            }
      responses:
        201:
          body:
            application/json:
              example:
    /{highlight_id}/messages:
      get:
        description: "Get all messages for the given highlight"
        responses:
          200:
            body:
              application/json:
                example: |
                  [
                    {
                      "user": {
                        "username": "harryliu",
                        "name": "Harry"
                      },
                      "comment": {
                        "body": "5555",
                        "createdAt": 123232412
                      }
                    }
                  ]
      post:
        description: "Add a message to the given highlight"
        headers:
          Username:
            description: Username of the user who created the comment
            example: harryliu
        body:
          application/json:
            example: |
              {
                "body": "5555"
              }
        responses:
          201:
            body:
              application/json:
                example:
